export enum ButtonClass {
    PRIMARY = 'btn btn-primary',
    SECONDARY = 'btn btn-secondary',
    SUCCESS = 'btn btn-success',
    DANGER = 'btn btn-danger',
    WARNING = 'btn btn-warning',
    INFO = 'btn btn-info',
    DARK = 'btn btn-dark',
    LIGHT = 'btn btn-light',
    LINK = 'btn btn-link',
    PRIMARY_OUTLINE = 'btn btn-outline-primary',
    SECONDARY_OUTLINE = 'btn btn-outline-secondary',
    SUCCESS_OUTLINE = 'btn btn-outline-success',
    DANGER_OUTLINE = 'btn btn-outline-danger',
    WARNING_OUTLINE = 'btn btn-outline-warning',
    INFO_OUTLINE = 'btn btn-outline-info',
    DARK_OUTLINE = 'btn btn-outline-dark',
    LIGHT_OUTLINE = 'btn btn-outline-light'
}